#!/bin/sh

uci set wireless.radio0.channel='auto'
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0.ssid='JDC-2.4G'
uci set wireless.default_radio0.encryption='psk-mixed'
uci set wireless.default_radio0.key='88888888'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.cell_density='0'
uci set wireless.default_radio1.ssid='JDC-5G'
uci set wireless.default_radio1.encryption='psk-mixed'
uci set wireless.default_radio1.key='88888888'

exit 0
